[tox]
envlist = py312

[testenv]
deps=
    pytest
    pytest-django
    Django>=5.1,<5.2
    django-mptt>=0.6,<1.0
    django_polymorphic==4.0.0
    django-js-asset==2.0.0
    easy-thumbnails>=2,<3.0
    Unidecode>=0.04,<1.2
    six
    filetype
commands=
    pytest \
        --junitxml={toxinidir}/pytest-results.xml \
        --ds=filer.test_settings \
        --pyargs \
        {posargs} filer.tests
